# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import atuador_pb2 as atuador__pb2


class AtuadorGRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.desligarLampada = channel.unary_unary(
                '/AtuadorGRPC/desligarLampada',
                request_serializer=atuador__pb2.LampadaRequest.SerializeToString,
                response_deserializer=atuador__pb2.LampadaResponse.FromString,
                )
        self.ligarLampada = channel.unary_unary(
                '/AtuadorGRPC/ligarLampada',
                request_serializer=atuador__pb2.LampadaRequest.SerializeToString,
                response_deserializer=atuador__pb2.LampadaResponse.FromString,
                )
        self.desligarArCondicionado = channel.unary_unary(
                '/AtuadorGRPC/desligarArCondicionado',
                request_serializer=atuador__pb2.ArCondicionadoRequest.SerializeToString,
                response_deserializer=atuador__pb2.ArCondicionadoResponse.FromString,
                )
        self.ligarArCondicionado = channel.unary_unary(
                '/AtuadorGRPC/ligarArCondicionado',
                request_serializer=atuador__pb2.ArCondicionadoRequest.SerializeToString,
                response_deserializer=atuador__pb2.ArCondicionadoResponse.FromString,
                )
        self.aumentarTemperatura = channel.unary_unary(
                '/AtuadorGRPC/aumentarTemperatura',
                request_serializer=atuador__pb2.ArCondicionadoRequest.SerializeToString,
                response_deserializer=atuador__pb2.ArCondicionadoResponse.FromString,
                )
        self.diminuirTemperatura = channel.unary_unary(
                '/AtuadorGRPC/diminuirTemperatura',
                request_serializer=atuador__pb2.ArCondicionadoRequest.SerializeToString,
                response_deserializer=atuador__pb2.ArCondicionadoResponse.FromString,
                )
        self.ligarHumidificador = channel.unary_unary(
                '/AtuadorGRPC/ligarHumidificador',
                request_serializer=atuador__pb2.HumidificadorRequest.SerializeToString,
                response_deserializer=atuador__pb2.HumidificadorResponse.FromString,
                )
        self.desligarHumidificador = channel.unary_unary(
                '/AtuadorGRPC/desligarHumidificador',
                request_serializer=atuador__pb2.HumidificadorRequest.SerializeToString,
                response_deserializer=atuador__pb2.HumidificadorResponse.FromString,
                )


class AtuadorGRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def desligarLampada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ligarLampada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def desligarArCondicionado(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ligarArCondicionado(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def aumentarTemperatura(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def diminuirTemperatura(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ligarHumidificador(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def desligarHumidificador(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AtuadorGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'desligarLampada': grpc.unary_unary_rpc_method_handler(
                    servicer.desligarLampada,
                    request_deserializer=atuador__pb2.LampadaRequest.FromString,
                    response_serializer=atuador__pb2.LampadaResponse.SerializeToString,
            ),
            'ligarLampada': grpc.unary_unary_rpc_method_handler(
                    servicer.ligarLampada,
                    request_deserializer=atuador__pb2.LampadaRequest.FromString,
                    response_serializer=atuador__pb2.LampadaResponse.SerializeToString,
            ),
            'desligarArCondicionado': grpc.unary_unary_rpc_method_handler(
                    servicer.desligarArCondicionado,
                    request_deserializer=atuador__pb2.ArCondicionadoRequest.FromString,
                    response_serializer=atuador__pb2.ArCondicionadoResponse.SerializeToString,
            ),
            'ligarArCondicionado': grpc.unary_unary_rpc_method_handler(
                    servicer.ligarArCondicionado,
                    request_deserializer=atuador__pb2.ArCondicionadoRequest.FromString,
                    response_serializer=atuador__pb2.ArCondicionadoResponse.SerializeToString,
            ),
            'aumentarTemperatura': grpc.unary_unary_rpc_method_handler(
                    servicer.aumentarTemperatura,
                    request_deserializer=atuador__pb2.ArCondicionadoRequest.FromString,
                    response_serializer=atuador__pb2.ArCondicionadoResponse.SerializeToString,
            ),
            'diminuirTemperatura': grpc.unary_unary_rpc_method_handler(
                    servicer.diminuirTemperatura,
                    request_deserializer=atuador__pb2.ArCondicionadoRequest.FromString,
                    response_serializer=atuador__pb2.ArCondicionadoResponse.SerializeToString,
            ),
            'ligarHumidificador': grpc.unary_unary_rpc_method_handler(
                    servicer.ligarHumidificador,
                    request_deserializer=atuador__pb2.HumidificadorRequest.FromString,
                    response_serializer=atuador__pb2.HumidificadorResponse.SerializeToString,
            ),
            'desligarHumidificador': grpc.unary_unary_rpc_method_handler(
                    servicer.desligarHumidificador,
                    request_deserializer=atuador__pb2.HumidificadorRequest.FromString,
                    response_serializer=atuador__pb2.HumidificadorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AtuadorGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AtuadorGRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def desligarLampada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AtuadorGRPC/desligarLampada',
            atuador__pb2.LampadaRequest.SerializeToString,
            atuador__pb2.LampadaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ligarLampada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AtuadorGRPC/ligarLampada',
            atuador__pb2.LampadaRequest.SerializeToString,
            atuador__pb2.LampadaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def desligarArCondicionado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AtuadorGRPC/desligarArCondicionado',
            atuador__pb2.ArCondicionadoRequest.SerializeToString,
            atuador__pb2.ArCondicionadoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ligarArCondicionado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AtuadorGRPC/ligarArCondicionado',
            atuador__pb2.ArCondicionadoRequest.SerializeToString,
            atuador__pb2.ArCondicionadoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def aumentarTemperatura(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AtuadorGRPC/aumentarTemperatura',
            atuador__pb2.ArCondicionadoRequest.SerializeToString,
            atuador__pb2.ArCondicionadoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def diminuirTemperatura(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AtuadorGRPC/diminuirTemperatura',
            atuador__pb2.ArCondicionadoRequest.SerializeToString,
            atuador__pb2.ArCondicionadoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ligarHumidificador(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AtuadorGRPC/ligarHumidificador',
            atuador__pb2.HumidificadorRequest.SerializeToString,
            atuador__pb2.HumidificadorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def desligarHumidificador(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AtuadorGRPC/desligarHumidificador',
            atuador__pb2.HumidificadorRequest.SerializeToString,
            atuador__pb2.HumidificadorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
