# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: atuador.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ratuador.proto\"\x10\n\x0eLampadaRequest\";\n\x0fLampadaResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\"\x17\n\x15\x41rCondicionadoRequest\"Q\n\x16\x41rCondicionadoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\x12\r\n\x05valor\x18\x04 \x01(\x02\"\x16\n\x14HumidificadorRequest\"A\n\x15HumidificadorResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\x32\xb6\x04\n\x0b\x41tuadorGRPC\x12\x36\n\x0f\x64\x65sligarLampada\x12\x0f.LampadaRequest\x1a\x10.LampadaResponse\"\x00\x12\x33\n\x0cligarLampada\x12\x0f.LampadaRequest\x1a\x10.LampadaResponse\"\x00\x12K\n\x16\x64\x65sligarArCondicionado\x12\x16.ArCondicionadoRequest\x1a\x17.ArCondicionadoResponse\"\x00\x12H\n\x13ligarArCondicionado\x12\x16.ArCondicionadoRequest\x1a\x17.ArCondicionadoResponse\"\x00\x12H\n\x13\x61umentarTemperatura\x12\x16.ArCondicionadoRequest\x1a\x17.ArCondicionadoResponse\"\x00\x12H\n\x13\x64iminuirTemperatura\x12\x16.ArCondicionadoRequest\x1a\x17.ArCondicionadoResponse\"\x00\x12\x45\n\x12ligarHumidificador\x12\x15.HumidificadorRequest\x1a\x16.HumidificadorResponse\"\x00\x12H\n\x15\x64\x65sligarHumidificador\x12\x15.HumidificadorRequest\x1a\x16.HumidificadorResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atuador_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LAMPADAREQUEST._serialized_start=17
  _LAMPADAREQUEST._serialized_end=33
  _LAMPADARESPONSE._serialized_start=35
  _LAMPADARESPONSE._serialized_end=94
  _ARCONDICIONADOREQUEST._serialized_start=96
  _ARCONDICIONADOREQUEST._serialized_end=119
  _ARCONDICIONADORESPONSE._serialized_start=121
  _ARCONDICIONADORESPONSE._serialized_end=202
  _HUMIDIFICADORREQUEST._serialized_start=204
  _HUMIDIFICADORREQUEST._serialized_end=226
  _HUMIDIFICADORRESPONSE._serialized_start=228
  _HUMIDIFICADORRESPONSE._serialized_end=293
  _ATUADORGRPC._serialized_start=296
  _ATUADORGRPC._serialized_end=862
# @@protoc_insertion_point(module_scope)
