# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\"w\n\x06\x44\x65vice\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\r\n\x05porta\x18\x04 \x01(\x05\x12\x19\n\x04tipo\x18\x05 \x01(\x0e\x32\x0b.DeviceType\x12\x0e\n\x06ligado\x18\x06 \x01(\x08\x12\r\n\x05valor\x18\x07 \x01(\x02*;\n\nDeviceType\x12\x0b\n\x07\x41TUADOR\x10\x00\x12\n\n\x06SENSOR\x10\x01\x12\x14\n\x10SENSOR_E_ATUADOR\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICETYPE._serialized_start=137
  _DEVICETYPE._serialized_end=196
  _DEVICE._serialized_start=16
  _DEVICE._serialized_end=135
# @@protoc_insertion_point(module_scope)
